### ISSUE TITLE
Changement de nom

### ISSUE THREAD

**Issue by Matyu9** [Cantina-Org/Nephelees#62]
[Néphélée](https://fr.wikipedia.org/wiki/N%C3%A9ph%C3%A9l%C3%A9es) : Nymphe des nuages (cloud)

**Comment by Timtonix** [comment]
Ça commence bien, le Neph c'est ok mais faudrait changer la fin

**Comment by Matbe9** [comment]
genre Neph c'est ok mais pas Néphélée

**Comment by Matyu9** [comment]
?
